import type { Config } from "tailwindcss";

const c = (name: string) => `rgb(var(--c-${name}) / <alpha-value>)`;

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: c("background"),
        surface: c("surface"),
        "surface-dim": c("surface-dim"),
        "surface-bright": c("surface-bright"),
        "surface-container-lowest": c("surface-container-lowest"),
        "surface-container-low": c("surface-container-low"),
        "surface-container": c("surface-container"),
        "surface-container-high": c("surface-container-high"),
        "surface-container-highest": c("surface-container-highest"),
        "surface-variant": c("surface-variant"),
        "on-surface": c("on-surface"),
        "on-surface-variant": c("on-surface-variant"),
        "on-background": c("on-background"),
        primary: c("primary"),
        "on-primary": c("on-primary"),
        "primary-container": c("primary-container"),
        "on-primary-container": c("on-primary-container"),
        secondary: c("secondary"),
        "secondary-container": c("secondary-container"),
        "on-secondary": c("on-secondary"),
        "on-secondary-container": c("on-secondary-container"),
        tertiary: c("tertiary"),
        "tertiary-container": c("tertiary-container"),
        "on-tertiary": c("on-tertiary"),
        "on-tertiary-container": c("on-tertiary-container"),
        outline: c("outline"),
        "outline-variant": c("outline-variant"),
        error: c("error"),
        "on-error": c("on-error"),
        "error-container": c("error-container"),
        "on-error-container": c("on-error-container"),
        "inverse-surface": c("inverse-surface"),
        "inverse-on-surface": c("inverse-on-surface"),
        "inverse-primary": c("inverse-primary"),
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        gutter: "16px",
        margin: "24px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        code: ['"Geist Mono"', "ui-monospace", "monospace"],
        "headline-lg": ['"Geist Mono"', "ui-monospace", "monospace"],
        "headline-sm": ['"Geist Mono"', "ui-monospace", "monospace"],
        display: ['"Geist Mono"', "ui-monospace", "monospace"],
        "label-caps": ['"Geist Mono"', "ui-monospace", "monospace"],
        "body-md": ['"Geist Mono"', "ui-monospace", "monospace"],
        "body-sm": ['"Geist Mono"', "ui-monospace", "monospace"],
      },
      fontSize: {
        code: ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        display: ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
